### ISSUE TITLE
qsv to ods

### ISSUE THREAD

**Issue by ondohotola** [dathere/qsv#865]
I would like to to be able to write to LibreOffice files in addition to Excel with the command of something like `qsv to ods filename.ods`

**Comment by jqnatividad** [comment]
Hi @kindly, are you planning to support ods with the `to` command?

It seems https://github.com/thscharler/spreadsheet-ods has some good coverage...

**Comment by kindly** [comment]
I will have a look at this feesability of this soon.

**Comment by ondohotola** [comment]
Can we revisit this, perhaps?

**Comment by ondohotola** [comment]
Cool, thanks

**Comment by jqnatividad** [comment]
@kindly , I'm getting a compilation error when I upgrade to 0.11.

https://github.com/dathere/qsv/actions/runs/14363120368/job/40269414972?pr=2673

Any hints?

**Comment by kindly** [comment]
@jqnatividad  It has not had any compilation errors for me, locally at least.  I am soon to upgrade my tool `flatterer` https://github.com/kindly/flatterer with it, which will do a lot more testing and may fail in actions too.  It is the ODS library I am using causing the issues, but the versions seen to align, so must be to do with rust version/platform/stability, but I can not tell easily the differences from that output.

**Comment by kindly** [comment]
@jqnatividad my guess its a `quick_xml` incompatibility with somthing else that is using it in qsv.

**Comment by jqnatividad** [comment]
@kindly it is the quick-xml dependency.

I also use the calamine crate (for reading Excel) which uses the encoding feature of quick-xml, and spreadsheet-ods doesn't.

I created a PR in spreadsheet-ods to fix it - https://github.com/thscharler/spreadsheet-ods/issues/58

Should that get merged, I'll be able to enable `to ods` support.
