### PR TITLE
Update deb package

### PR DESCRIPTION
**Pull request by tino097**
We will include qsv, qsvdp, qsvlite in the deb package

### CODE REVIEW

**Comment by tino097** [comment]
```
   --> src/cmd/sortcheck.rs:115:9
    |
115 |         record_count = if show_progress {
    |         ^^^^^^^^^^^^
    |
    = help: maybe it is overwritten before being read?
    = note: `#[warn(unused_assignments)]` on by default

error[E0384]: cannot assign twice to immutable variable `record_count`
   --> src/cmd/sortcheck.rs:126:9
    |
115 | /         record_count = if show_progress {
116 | |             let count = util::count_rows(&rconfig)?;
117 | |             util::prep_progress(&progress, count);
118 | |             count
...   |
121 | |             0
122 | |         };
    | |_________- first assignment to `record_count`
...
126 |           record_count = 0;
    |           ^^^^^^^^^^^^^^^^ cannot assign twice to immutable variable
    |
help: consider making this binding mutable
    |
105 |     let mut record_count;
    |         +++

For more information about this error, try `rustc --explain E0384`.
warning: `qsv` (bin "qsv") generated 1 warning
error: could not compile `qsv` (bin "qsv") due to 1 previous error; 1 warning emitted
cargo-deb: build failed
```
After merging master in the branch, when im running `cargo deb` im getting this error

**Comment by tino097** [comment]
I will need to test it

File: Cargo.toml [hunk 1]
```diff
@@ -390,7 +390,24 @@ maintainer           = "Konstantin Sivakov <konstantin@datHere.com>"
 copyright            = "2024, datHere Inc. <www.dathere.com>"
 extended-description = """A high performance CSV data-wrangling toolkit."""
 depends              = "$auto"
-features             = ["feature_capable"]
 section              = "utility"
 priority             = "optional"
-assets               = [["target/release/qsv", "/usr/local/bin/", "755"]]
+
+# Default feature and asset
+features             = ["feature_capable"]
```
Comment (jqnatividad) [inline Cargo.toml:414]: You may want to add the features you actually want to enable. Otherwise, this is just like qsvlite.
I suggest to add everything EXCEPT python, as doing so creates a runtime dependency on the specific version of python libraries being present at startup, even if you're not using the `py` command:

`["feature_capable","apply","fetch","foreach","geocode","lens","luau","polars","prompt","to"]`

You can also enable the `python` feature if you can specify cargo-deb to have a dependency on the specific version of python you need to be installed in the config.

**Review by jqnatividad — CHANGES_REQUESTED** [review]

**Review by jqnatividad — APPROVED** [review]
